export { default as Emoji } from './emoji.png'
export { default as Bejou } from './projects/bejou.png'
export { default as Celebrations } from './projects/celebrations.png'
export { default as Dreamplex } from './projects/dreamplex.png'
export { default as Edutek } from './projects/edutek.png'
export { default as HHG } from './projects/hhg.png'
export { default as HiepHuong } from './projects/hiephuong.png'
export { default as KGN } from './projects/kgn.png'
export { default as OneCacao } from './projects/one-cacao.png'
export { default as OneMatcha } from './projects/one-matcha.png'
export { default as OneCoffee } from './projects/one-coffee.png'
export { default as One } from './projects/one.png'
export { default as PhoLovers } from './projects/projects-pholovers.png'
export { default as Tankimsu } from './projects/tankimsu.png'

export const ONE_PROJECT = 'https://i.imgur.com/aEdSJ4f.png'
export const ONE_MATCHA = 'https://i.imgur.com/hlJ8L7R.png'
export const ONE_COFFEE = 'https://i.imgur.com/PoP5CFz.png'
export const EDUTEK = 'https://i.imgur.com/OXM0aXU.png'
export const HIEP_HUONG = 'https://i.imgur.com/j6cKr2N.png'
export const MARKEE_RESTAURANT = 'https://i.imgur.com/rvjQHBM.png'
export const KGN_COFFEE = 'https://i.imgur.com/OkptHBN.png'
export const CELEBRATIONS = 'https://i.imgur.com/ektbCcO.png'
export const VINPEARL_LUXURY = 'https://i.imgur.com/il5Zg3X.png'
export const VINPEARL_VOUCHER = 'https://i.imgur.com/zC4xqrM.png'
export const JANET_STUDIO = 'https://i.imgur.com/GVbPuO5.mp4'
export const CHUYEN_XE_NHAN_SAC = 'https://i.imgur.com/4PTN7Oy.mp4'
