// Branding Logo
export { default as BayKateLogo } from './client/bay-kate.svg'
export { default as BejouLogo } from './client/bejou.svg'
export { default as HhgLogo } from './client/hhg.svg'
export { default as MarkeeLogo } from './client/markee.svg'
export { default as OneLogo } from './client/one.svg'
export { default as PhoLoversLogo } from './client/pho-lovers.svg'
export { default as SgMediaLogo } from './client/sg-media.svg'
export { default as TanAnhTienLogo } from './client/tan-anh-tien.svg'
export { default as TanKimSuLogo } from './client/tan-kimsu.svg'
export { default as VinpearlLogo } from './client/vinpearl-luxury.svg'
export { default as MapasLogo } from './mapas-logo.svg'
export { default as CaoKyLogo } from './client/cao-ky.svg'
export { default as EdutekLogo } from './client/edutek.svg'
export { default as KingdomLogo } from './client/kingdom.svg'

export { default as BayKateLogoBlack } from './client/bay-kate-black.svg'
export { default as BejouLogoBlack } from './client/bejou-black.svg'
export { default as HhgLogoBlack } from './client/hhg-black.svg'
export { default as PhoLoversLogoBlack } from './client/pho-lovers-black.svg'
export { default as SgMediaLogoBlack } from './client/sg-media-black.svg'
export { default as VinpearlLogoBlack } from './client/vinpearl-luxury-black.svg'
export { default as CaoKyLogoBlack } from './client/cao-ky-black.svg'
export { default as EdutekLogoBlack } from './client/edutek-black.svg'
export { default as OneLogoBlack } from './client/one-black.svg'
export { default as KingdomLogoBlack } from './client/kingdom-black.svg'

// Icons
export { default as SettingIcon } from '@/assets/svg/icon/setting.svg?react'
export { default as ImageQuantityIcon } from '@/assets/svg/icon/number-images.svg'
export { default as DoubleArrowIcon } from '@/assets/svg/icon/DoubleArrowIcon'

export { default as FaceBookLogo } from '@/assets/svg/icon/facebook.svg?react'
export { default as ArrowIcon } from '@/assets/svg/icon/arrow.svg?react'
